### PR TITLE
Support nested modules

### PR DESCRIPTION
**Pull request by aaronfischer**
Forked off #780 (due to inactivity), but added a simple test to verify nested models/factories can be reached.

In the testing app visit /pets/dogs.
In mirage the models/factories are setup as follows:

```
- /models
-- contact.js
-- blog-post.js
-- /pet
--- dog.js
...
```

### CODE REVIEW

**Comment by samselikoff** [comment]
Sorry about the delay - could we get a rebase, then I think this is good to merge! Anything else I need to know?

**Comment by Aaronfischer** [comment]
@samselikoff All good, sorry about MY delay now. This should be rebased..

Only thing to note, and I didn't dive in to refactor this because I have no clue where to start... is that if you put the mirage models into subdirectories and access them that way, Mirage does not properly handle the pluralization as it relates to following jsonapi spec... (Mirage's internal object names/schema/etc)
I didn't find this to be a huge problem when using, but perhaps my use-case wasn't as "exhaustive" as others may be.

**Comment by samselikoff** [comment]
Dangit, let this slip again. I will insta-merge if you can rebase & shape it up again...apologies.

We can iterate & make it more exhaustive as folks run into issues.

**Comment by brunowego** [comment]
Ping @Aaronfischer. 👍

**Comment by Rastopyr** [comment]
Any updates? 😺 
@Aaronfischer @brunowego @samselikoff

**Comment by Aaronfischer** [comment]
@samselikoff This should now be rebased. How are you handling codeclimate issues like the above?
Getting a bunch of ES6 issues.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1785 closes

**Pull request closed without merging**
