### PR TITLE
Add noop initializer when mirage is excluded from build

### PR DESCRIPTION
**Pull request by kennethdavidbuck**
This is my first attempt at addressing #1210.

@rwjblue would you be up for taking an initial peak at what I have so far? I have taken a pretty simple approach to start with here. This is also the first time that I have attempted to write a test(s) to cover the state of a broccoli tree. Any / insight feedback would be appreciated. Thank you in advance.

### CODE REVIEW

**Comment by samselikoff** [comment]
This looks great!

Since the current initializer only runs `startMirage` if `shouldUseMirage` is true, do we need to replace it with the noop? (It essentially is a noop). That keeps all the initializer logic within the initializer, and lets you remove the `replace` logic from `index.js`.

**Comment by kennethdavidbuck** [comment]
@samselikoff , thanks! The reason why I am replacing the entire initializer is because it imports code that doesn't exist in production builds (since everything gets pruned) which, if I remember correctly, leads to missing import errors etc. The idea was to strip all references. I am completely open to trying any alternatives/suggestions you might have for that. Thanks again!

**Comment by samselikoff** [comment]
Ah, right you are. Let's go with this approach for now. Thanks!

**Comment by kennethdavidbuck** [comment]
My pleasure, and thank you!

**Comment by HodofHod** [comment]
This change causes a massive performance hit (~15s) to my warm builds even when `excludeFilesFromBuild` is true. The logs indicate that returning a tree from `treeFor` causes `lodash` (and other dependencies) to be funneled into the build, even though they don't end up in the vendor.js. Besides for that, SimpleReplace (from `broccoli-string-replace`) takes about ~7s (running on multiple trees).

This is on ember-cli@3.3.0, development build.

```
Build successful (44671ms)

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel: lodash (1)                             | 9446ms
broccoli-persistent-filter:SimpleReplace (5)  | 6764ms (1352 ms)
Babel: my-app (5)                             | 3899ms (779 ms)
```


Using 
```js
addons: {
  blacklist: [
    EmberApp.env() === 'test' ? "" : "ember-cli-mirage"
  ],
}
```
seems to be the way to do it.

**Comment by samselikoff** [comment]
Yeesh. Opened an issue to track.

**Comment by samselikoff** [comment]
@HodofHod https://github.com/samselikoff/ember-cli-mirage/pull/1410 should fix it! Let me know if you run into anything else related to this 👍

**Comment by HodofHod** [comment]
@samselikoff That's amazing, thank you!

**Pull request merged**
