### PR TITLE
Add HEAD request route handler shorthand.

### PR DESCRIPTION
**Pull request by timjcook**
refers to #723
 
- [x] Added head request shorthand
 - returns 204 if resource was found
 - returns 404 if a resource was expected to be found but wasn't

### CODE REVIEW

**Comment by samselikoff** [comment]
Thanks for working on this!

Do the shorthands make sense for HEAD? Is HEAD ever used to return resources like GET is?

**Comment by timjcook** [comment]
@samselikoff I don’t think so, as far as I can tell a `HEAD` request will never return any content in the message body, just the status code along with other meta data. I’m not quite sure what the correct status code to return is for this request. Some suggest it should mirror the `GET` request to the same route, but rails seems to always return a `204`, hence my initial commit, but happy to change if others think differently. My use case only required a successful response so the action could proceed.

**Comment by samselikoff** [comment]
In this case in might make sense to not add shorthands at all, just the actual `this.head` method and let folks do something like

```js
this.head('/users', undefined, 204);
```

The shorthands are meant to interact with db data.

What do you think?

**Comment by timjcook** [comment]
I think that would be a fair way to do it and would remove the overhead of an extra handler. However it would, I think, introduce the possibility that someone could stub out say a route like:
```javascript
this.head('/users/:id', undefined, 204);
```
and always return `204`'s, but then if they didn't set up a `User` in their scenario and they made a get request to that route, it would return a `404`, which would be inconsistent with a real API.
So I guess we would be relying on people setting up their test environment correctly.

**Comment by samselikoff** [comment]
Ohhh I see - I totally didn't understand your original point that the shorthand just responds with the correct status code, but an empty body. This looks great to me.

I'd say, let's just delete the array shorthand & tests. Doesn't really make sense here. (I don't really like the array shorthand anymore on any of the verbs tbh, now that we have orm & serializers)

**Comment by timjcook** [comment]
Fantastic, I've removed the array shorthand and tests now so hopefully it is ready to go. Just let me know if you think it needs anything more.

**Comment by samselikoff** [comment]
:+1: thank you!

**Pull request merged**
