### PR TITLE
Only _definePlainAttribute if not an association

### LINKED ISSUE #1061: One-to-One relationship causes stack size exceeded
Here's a reproduction in a [simple ember app](https://github.com/timhaines/mirage-recursive-bug)

There are two models - organization and subscription, that have a 1-1 belongsTo relationship. When Mirage tries to load the organization model as a result of the schema.organizations.all() call, the maximum stack size exceeded error occurs.

When I last dug into this, it appeared the problem was related to the model get and set methods in belongsTo.js.  In my basic understanding, when the model is being created, within _setupRelationships, setting the model calls `inversesAlreadyAssociated`, which results in a call to getting the model, which in turn calls `find` on the model in this line:
`model = association.schema[toCollectionName(association.modelName)].find(foreignKeyId);`

### PR DESCRIPTION
**Pull request by ivanvanderbyl**
Fixes #1061 and a loading delay when using this in development which causes the browser to hang.

### CODE REVIEW

**Comment by samselikoff** [comment]
Awesome, thanks for this!

Is the build broken because of Node 4?

**Comment by ivanvanderbyl** [comment]
It looks like a dependency failed to install, needs a kick.

**Comment by workmanw** [comment]
Bump. I ran into this issue while trying to upgrade. Took me an hour to track down and it turns out someone else beat me to the punch :). I can confirm this fixes my issue.

**Comment by workmanw** [comment]
Second shameless bump. This is blocking me from going to 0.3.x.

**Comment by samselikoff** [comment]
Restarting build, my apologies

**Comment by samselikoff** [comment]
Failures again, could someone investigate?

**Comment by workmanw** [comment]
At first look it seemed like a Node 4 issue, but I think it's actually a NPM 2 issue 😬 . Honestly, I'm not sure what to do about resolving it. It seems to be a pure dependency resolution issue.

**Comment by rwjblue** [comment]
@workmanw - I believe that the simplest solution here would be to update `npm` in CI which is what a new `ember addon foo` project would do ([see here](https://github.com/ember-cli/ember-cli/blob/1314f8b64c613fac408428d0c0296b175bb9a165/blueprints/addon/files/.travis.yml#L44)).

**Comment by workmanw** [comment]
@rwjblue Ah. Yes, that makes perfect sense. Thank you!!

Let me submit a PR right meow 😸 .

**Comment by workmanw** [comment]
Oh, actually I just realized that master now uses `yarn` instead of `npm`. So I think we just need to rebase this commit. 

@ivanvanderbyl Would you mind rebasing?

**Comment by ivanvanderbyl** [comment]
@workmanw @samselikoff rebased. Should be good to merge now 👍

**Comment by samselikoff** [comment]
🙇

**Pull request merged**
