### PR TITLE
Implement traits

### PR DESCRIPTION
**Pull request by Azdaroth**

### CODE REVIEW

**Comment by Azdaroth** [comment]
Solves https://github.com/samselikoff/ember-cli-mirage/issues/852

Works pretty fine, but passing arguments and extracting them based on their types in `create` and `build` is a bit painful... I was wondering if it's worth checking the sequence of the arguments (e.g. that there: traits, attr overrides and collectionFromCreateList) and not (collectionFromCreateList, traits, overrides), but seemed not really worth it comparing to the complexity it would introduce. Currently it actually doesn't matter and all these variants would work. The only surprising thing would be passing more than 1 `collectionFromCreateList` to `create` or passing more than 1 `overrides` as only the first argument of given type would be picked. But again, didn't want to make the arguments extraction too complex, I think it is quite unlikely there would be any issue with that.

Let me know what you think.

**Comment by samselikoff** [comment]
Amazing work man! Going to wait just a bit in case there are more comments on #852, then will take a look and get this merged. Super excited to get this in here.

**Comment by samselikoff** [comment]
Great work. I think the extraction is okay for now, `collectionFromCreateList` is an internal thing that is used so `db.collection` doesn't need to be called each time in the loop for `createList` (`db.collection` does a JSON.stringify copy of the entire db collection, so it's expensive).

**Comment by samselikoff** [comment]
🎊

**Comment by Azdaroth** [comment]
🎉

**Pull request merged**
