### PR TITLE
patching pretender so it does not store requests

### PR DESCRIPTION
**Pull request by bekzod**
attempt to solve #510

### CODE REVIEW

**Comment by Leooo** [comment]
@samselikoff we are fighting for months because we have memory leaks in our tests "somewhere". If this PR helps in any way, can it be merged?

**Comment by samselikoff** [comment]
I don't want to monkey patch Pretender here, and others might be relying on those APIs from the pretender instance.

Could you help by moving the [upstream PR](https://github.com/pretenderjs/pretender/pull/141) along? Once we get the option there it will be simple to expose it on Mirage.

Also if you need something immediately, you can run the above code in an initializer or your moduleForAcceptance.

**Comment by Leooo** [comment]
@samselikoff I've no Idea how to modify tests in the pretender repo unfortunately, see https://github.com/pretenderjs/pretender/pull/141.

**Comment by samselikoff** [comment]
Going to wait for Pretender to add this and set a default from within Mirage

**Pull request closed without merging**
