### PR TITLE
Generated function to generate a random number in a range

### PR DESCRIPTION
**Pull request by IAmJulianAcosta**
Created new PR for this functionality with a single commit

### CODE REVIEW

**Comment by samselikoff** [comment]
ah, new PR. next time you can just `git rebase -i HEAD~3` and use `squash` to squash your commits

**Comment by samselikoff** [comment]
thanks!

**Comment by IAmJulianAcosta** [comment]
You're welcome! I tried to squash them but not worked well, I'm not that good using git.

I want to ask you something, how this work? When you merge this pull request, the changes will be available in npm immediately?

**Comment by samselikoff** [comment]
Yes, they are now in `master`, so as long as you install mirage#master via

```js
// package.json
"ember-cli-mirage": "samselikoff/ember-cli-mirage"
```

or, more safely, by referencing the particular commit that contains your PR

```js
// package.json
"ember-cli-mirage": "samselikoff/ember-cli-mirage#15b98edbf24abca7e68eb0415d956f0d6a45f1db"
```

then run `npm install` and you'll have the feature you've added.

Note that installing from master is less stable than using a specific tag (e.g. `0.1.8`). Just wanted you to be aware.

**Pull request merged**
