### PR TITLE
fix auto-discovery of nested ember-data models

### PR DESCRIPTION
**Pull request by ro0gr**
Currently while discovering `ember-data` models mirage registers found model under its leaf name. For example if you have a `pet/dog` ember-data model it will be accessible as `schema['dog']`. This causes some exceptions while I try to use `ember-cli-mirage`.

After this change you can access nested model like `schema['pet/dog']`.

### CODE REVIEW

**Comment by ro0gr** [comment]
@offirgolan I would appreciate your 👀 here when you have time

**Comment by ro0gr** [comment]
@samselikoff what can I do to get it merged?

**Comment by samselikoff** [comment]
Thank you!

**Comment by ro0gr** [comment]
🎉

**Pull request merged**
