### PR TITLE
Inject Faker into the Mirage.Factory attribute's closure

### PR DESCRIPTION
**Pull request by mupkoo**
Inject Faker into the Mirage.Factory attribute's closure, so you can do something like

```javascript
export default Mirage.Factory.extend({
  name: () => { return this.faker.name.firstName() }
});
```

Let me know what do you think and I will add it do the documentation.

### CODE REVIEW

**Comment by samselikoff** [comment]
Thanks for the PR! I'm wondering if we can make it even simpler, something like

```js
import Mirage, {faker} from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  name: faker.name.firstName
});
```

**Comment by samselikoff** [comment]
I've also thought it would be nice to have some way to specify a list of data to pull from, is this possible with Faker? For example, I like seeding my dev database with actual ted events so I can see what the UI will actually look like. I've done something like this before

```js
export default Mirage.Factory.extend({
  title: i => {
    var list = [
      'TED2011',
      'TED Women 2011',
      'TED Global 2012',
      'TED 2013',
      'TED 2014',
      'TED Active 2014'
    ];
    return list[i % list.length];
  }
});
```

but it would be really nice to be able to do

```js
export default Mirage.Factory.extend({
  title: faker.list(
    'TED2011',
    'TED Women 2011',
    'TED Global 2012',
    'TED 2013',
    'TED 2014',
    'TED Active 2014'
  )
});
```

or something like that.

**Comment by mupkoo** [comment]
Importing faker looks and feels better. The latest version exports fakers, so you can do it like you mentioned.

```javascript
import Mirage, {faker} from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  name: faker.name.firstName
});
```

But the project is using an old version of Babel, so I had the dummy test app I have two imports like so

```javascript
import Mirage from 'ember-cli-mirage';
import { faker } from 'ember-cli-mirage';
```

As for the list helper, I created a helper method which gets exported as well. You can now do something like that and it will select a value from the list you have provided (the example will work with Babel 5)

```javascript
import Mirage, { cycle } from 'ember-cli-mirage';

export default Mirage.Factory.extend({
   title: cycle('TED2011', 'TED2012')
});
```

If you think it's better to name it list or/and merge it into faker, let me know.

**Comment by mupkoo** [comment]
I had a change of hearts and decided to integrate list helpers into faker, but I created two helpers - random and cycle. One selects a random value from a list, the other one cycles them.

```javascript
import Mirage, { faker } from 'ember-cli-mirage';

export default Mirage.Factory.extend({
   name: faker.list.random('Jane', 'John'),
   age: faker.list.cycle(30, 40, 50)
});
```

**Comment by samselikoff** [comment]
love this, exactly what I was thinking! thanks for your help!

**Comment by seanpdoyle** [comment]
This looks great!

**Comment by mupkoo** [comment]
Thank you @seanpdoyle 

@samselikoff do you want me to create a PR with an update to the docs explaining about faker?

**Comment by samselikoff** [comment]
@mupkoo that would be great! Since it's a backwards-compatible new feature we'll release it in 0.1.3, but let's not worry about making a new version of the docs for 0.1.2. We should add a note that says `Added in 0.1.3` somehow. You can look at the other `<aside>` tags, or make your own banner for this.

**Comment by samselikoff** [comment]
And we should also make Latest say `Latest (0.1.x)`

**Comment by mupkoo** [comment]
Ok. Can you tell me where I can find the documentation?

**Comment by samselikoff** [comment]
yep `gh-pages` branch

**Comment by seawatts** [comment]
@mupkoo Any updates on the docs?

**Comment by mupkoo** [comment]
@seawatts I haven't had any free time those days, but I think I will manage to create a PR this week

**Comment by seawatts** [comment]
@mupkoo :+1: Thanks!

**Comment by samselikoff** [comment]
@mupkoo @seawatts I'm taking care of this, almost had it finished last night but will wrap up today. I want everything to be under a `v0.1.x` docset with new features indicated with a banner. 

Should have something pushed today or tomorrow.

btw, <3 this PR, been using it a lot and it's awesome!

**Comment by samselikoff** [comment]
faker docs added: http://www.ember-cli-mirage.com/docs/v0.1.x/factories/#using-fakerjs

**Comment by seawatts** [comment]
Woot :+1:

**Comment by mupkoo** [comment]
Awesome! :+1: :)

**Pull request merged**
