### PR TITLE
[FEATURE] Add mirage-factory and mirage-fixture blueprints

### PR DESCRIPTION
**Pull request by trabus**
This PR adds blueprints for mirage-factory and mirage-fixture as described in #51

I don't have any tests for them yet, would you like me to add the blueprint testing helpers so they can be tested?

### CODE REVIEW

**Comment by trabus** [comment]
I have a few things I'd like to add to this before it's ready. I'm going to add a description as well as the ability to pass params to generate factory properties. 

It would also be possible to add to the config when adding a fixture, similar to how the route blueprint generation adds your route to the router.js (thanks to @abuiles).

**Comment by samselikoff** [comment]
That sounds awesome! Definitely give it a shot if you're up for it

**Comment by samselikoff** [comment]
What about `m-fixture` and `m-factory` as aliases? (other ideas?) I know programmers hate to type...

**Comment by trabus** [comment]
I'd be fine with fixture and factory personally. How about tests? I don't want to drag all that setup code in for testing without your okay first.

**Comment by samselikoff** [comment]
I actually don't know how tests work for blueprints, you're saying to make sure they actually generate the files? I'm ok without them for now.

**Comment by trabus** [comment]
Yeah, they run in mocha, generating an ember app, then running the generate command to verify the contents. Not very important for simple blueprints, but when the blueprint modifies exisiting content (like the route blueprint), or has complex rules to generate content (like the model blueprint), it's probably good to have.

I've actually got some more pressing things to work on right now, so I'm thinking I'll take the additional functionality I've listed above and break it into another issue to implement later. Then we can take the time to add the additional support for the tests.

**Comment by samselikoff** [comment]
gotcha - so I can go ahead and merge this, and we'll track the other features in a different issue?

**Comment by trabus** [comment]
Actually let me change the blueprint names to fixture and factory first.

**Comment by trabus** [comment]
I went with factory and fixture. I looked through and there was only one other project using a fixture blueprint and it's not likely the two projects would be used together.

This is ready to go :+1:

**Comment by samselikoff** [comment]
thanks mate!

**Pull request merged**
