### PR TITLE
custom identity managers per application and/or model

### PR DESCRIPTION
**Pull request by jelhan**
Adds support for custom identity managers per application and/or per model as asked for in #960. PR is based on v0.3.0-beta.4.

### CODE REVIEW

**Comment by jelhan** [comment]
Rebased against v0.3.1 and changed base branch.

**Comment by samselikoff** [comment]
Wow this is great. Going to make time to look at this soon.

**Comment by jelhan** [comment]
Rebased against current master. @samselikoff did you had any time to look at this one?

**Comment by samselikoff** [comment]
Restarting stalled build, when it passes we can merge!

**Comment by samselikoff** [comment]
@jelhan Any chance you could write up some docs for this? Even just a markdown comment here that's a simple overview, and I can take care of porting it into the docs

**Comment by jelhan** [comment]
@samselikoff You are currently rewriting docs aren't you? Should I open a MR against `new-docs-site` branch or should I just wait until that one has been merged?

**Comment by samselikoff** [comment]
You can PR to current site and I can port over. I’m close to done but you know how these things go, if it’s another month I’d rather have it on the current site 👍

**Pull request merged**
