### PR TITLE
Fix _findRecord to account for IDs which are numeric but saved as strings

### PR DESCRIPTION
**Pull request by mydea**
When having a database with IDs which are strings but possibly numeric, the _findRecord(id) function would not find a record because the passed in ID is converted to an integer but the record's ID is not.

e.g. if you have a record: 

```json
{ 
    id: "20", 
    name: "Hello" 
}
```

It was impossible to fetch it via its ID.
This pull request will also convert the record ID to an integer the same way the id parameter is converted, which fixes this issue.

### CODE REVIEW

**Comment by samselikoff** [comment]
Thanks for the PR! I'm not sure if you've seen https://github.com/samselikoff/ember-cli-mirage/issues/67 for some background on this issue.

Question, how are you getting string ids into your db? Are you using fixture files?

**Comment by mydea** [comment]
I am using factories & fixtures together like this:

```js
// app/mirage/scenarios/default.js

import fixtures from "my-app/fixtures/dummy-data";

export default function() {
    fixtures.users.forEach((user) => {
        server.create("user", user);
    });

    // ...
}
```

And in my fixtures file, I have mixed ids (some strings, some numbers), but I always use strings (e.g. `"1"`).

I am also having issues with the default shorthands, e.g. when using the ´put` shorthand updating does not work correctly because of the string ids.

**Comment by samselikoff** [comment]
yeah. So I think what we should do is coerce all ids to strings when storing in db, and then in your serializer you can change ids to ints if you so choose.

I can make this change after JSONAPISerializer lands, and I document the orm/serializer stuff.

**Comment by mydea** [comment]
Yeah, this sounds good. Looking forward to the Serializer API!

**Comment by jherdman** [comment]
@samselikoff I believe this should be resolved since #462 , aside from the HEAD alias.

**Comment by samselikoff** [comment]
Yes, you're right. Thanks!

**Pull request closed without merging**
