### PR TITLE
refactor(jQuery): Remove $.ajax, use async/await, move custom paths t…

### PR DESCRIPTION
**Pull request by geekygrappler**
…o their own test

- I wanted to remove $.ajax, so replaced it with fetch
- Used async/await hopefully makes the tests easier to follow
- We were testing custom paths using `posts` model in every test, moved testing of this behaviour into it's own test and removed from all other tests.

### CODE REVIEW

**Comment by geekygrappler** [comment]
It was bugging me that we had $.ajax in there and were not using async/await, so I fixed it for this file. It does introduce `ember-fetch` though, maybe you don't want that dependency @samselikoff?

**Comment by rwjblue** [comment]
This seems good to me, but generally speaking the only reason `ember-fetch` works is because it still uses `XMLHttpRequest` under the hook (e.g. it is not a "true" polyfill for native `fetch`). We need to create a pretender adapter for `fetch` (I think @cibernox had a spike of this at one point).

I'm _slightly_ concerned about landing these changes considering that I am _also_ pushing to use native `fetch` if the host apps targets support it.

Some background links:

* https://github.com/pretenderjs/pretender/issues/60
* https://github.com/ember-cli/ember-fetch/issues/45
* https://github.com/ember-cli/ember-fetch/pull/63
* https://github.com/samselikoff/ember-cli-mirage/issues/983

**Comment by cibernox** [comment]
I did. I can't locate it, but it's nothing I can't reproduce within a couple hours. The web community in general, not only the Ember community, needs a fetch stub that works.

**Comment by geekygrappler** [comment]
Thanks for taking a look @rwjblue.

> I am also pushing to use native fetch if the host apps targets support it.

Does that require some work on Pretender first to intercept native `fetch` requests?

From reading the links, I guess my only concern now would be that `ember-fetch` stops using `XMLHttpRequest`, and uses native `fetch` which would mean these tests break... I think.

In any case I think I'll split this into 3 different PRs. I think we can get the async/await changes and the moving of the custom paths merged fairly easily. The `fetch` stuff can wait.

**Comment by rwjblue** [comment]
Sounds good, thanks for working on this!

**Pull request closed without merging**
