### PR TITLE
Fixes generated code for destroy app helper

### PR DESCRIPTION
**Pull request by NLincoln**
I ran into this issue when writing unit tests for an initializer.

### CODE REVIEW

**Comment by HeroicEric** [comment]
Thanks for the help @NLincoln 😄  Can you please provide a description of the problem that this solves?

It also looks like you accidentally commited a `yarn.lock` file

**Comment by NLincoln** [comment]
Initializer tests use `startApp` and `destroyApp`, but mirage doesn't create the server global in those cases, causing errors.

**Comment by NLincoln** [comment]
Lockfile has been removed

**Comment by samselikoff** [comment]
Thanks @NLincoln!

Thank you for the review @HeroicEric , it really helps 😄

**Pull request merged**
