### PR TITLE
Warn that passthrough only works with jQuery > 2.x

### PR DESCRIPTION
**Pull request by LevelbossMike**
This took me some time to figure out and find in the issues. I suppose this is something that a lot of people need (passthrough option) and might run into.

### CODE REVIEW

**Comment by samselikoff** [comment]
hm is that true? I just created a brand new 1.13.8 app thats using jQuery 1.11.3 and passthrough works

**Comment by samselikoff** [comment]
maybe it should be `this.pretender.get('/api/v1', this.pretender.passthrough);`

**Comment by LevelbossMike** [comment]
I had this problem in an app of mine today. I had problems with ember-simple-auth + pretender and the promise (for the token endpoint) that should have resolved didn't with jquery 1.x and with 2.x it worked.

Maybe simple-auth is doing something special that doesn't work with passthrough and jquery 1.x but as far as I debugged it it only waits for a successful response and resolves in the hook that wasn't called for me.

I updated jquery after finding this: https://github.com/samselikoff/ember-cli-mirage/issues/219#issuecomment-126106993 which links to this [issue in the pretender repo](https://github.com/pretenderjs/pretender/issues/85) and the issue went away

The use case I have is migrating an app from http-mocks via ember-cli to mirage and we want to do this resource by resource. So I figured other people might run into this as well.

**Comment by samselikoff** [comment]
yah definitely. I see, post, let me try that. thanks for investigating mike!

**Comment by LevelbossMike** [comment]
I have created a repository that demonstrates the problem. I am not sure if I am doing something wrong here but when using passthrough the app does not load unless I install jquery >= 2.x

https://github.com/LevelbossMike/mirage-test

This also fails for a get request and does not seem to be a problem of post requests.

**Comment by sglanzer** [comment]
I hit this problem as well - using mirage for all but one API call (to an ember-cli http-mock that reads from the file system) - passthrough wouldn't resolve the promise until I upgraded to jquery 2.x

**Comment by samselikoff** [comment]
Sorry, I need to review this. Was trying to wrap up other things first but I should carve out some time for this.

**Comment by sglanzer** [comment]
No sweat, easy workaround (for me) - by the way, this addon is so ridiculously useful; really great work!

**Comment by jkeen** [comment]
Ran into the same issue: passthrough wasn't firing the callbacks on jQuery 1.11.3, and upgrading to 2.1.4 after finding the pretender issue fixed the problem. A console warning would be super helpful. :+1:

**Comment by olivierlesnicki** [comment]
having the same issue ... @samselikoff any progress on the review?

**Comment by samselikoff** [comment]
Seems like y'all verified it's true, though I swear I had it working on < 2. I'll merge this in, sorry yall! And thanks for opening issues.

**Comment by olivierlesnicki** [comment]
@samselikoff the root cause is actually a pretender issue: https://github.com/pretenderjs/pretender/issues/85 (for which I'm offering the following fix https://github.com/pretenderjs/pretender/pull/114)

**Pull request merged**
