### PR TITLE
Nested include normalization

### PR DESCRIPTION
**Pull request by jembezmamy**
It's just a continuation of #1323 adding support for nested includes (`?include=happy_user.happy_avatar`). I moved the dasherization to the very beginning of the includes graph building process.

First commit adds a failing test, second - the solution.

### CODE REVIEW

**Comment by iezer** [comment]
👍 this fixes an issue I'm currently having. Thanks @jembezmamy, would love to see this released.

**Comment by samselikoff** [comment]
@jembezmamy looks great, thank you!

Any idea about the `yarn.lock` changes?

**Comment by samselikoff** [comment]
I think you might be on an older version of yarn that doesn't have `integrity` keys?

**Comment by samselikoff** [comment]
Sweet! Thank you 👍

**Pull request merged**
