### PR TITLE
Add documentation for scenarios feature.

### PR DESCRIPTION
**Pull request by g-cassie**
Please rewrite/edit as much as wanted.  Just wanted to make sure this didn't get left out of the docs.

### CODE REVIEW

**Comment by seawatts** [comment]
How do you switch between scenarios?

**Comment by g-cassie** [comment]
On `default` scenario is supported for now.

**Comment by seawatts** [comment]
Oh alright, cool. Might want to mention that in the docs.

On Mon, Jun 1, 2015 at 12:44 PM, Gordon Cassie <notifications@github.com>
wrote:

> On default scenario is supported for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samselikoff/ember-cli-mirage/pull/143#issuecomment-107682131>
> .
>



-- 
*Chris Watts* | Software Engineer | cwatts@simplymeasured.com

**Comment by g-cassie** [comment]
Will do - I think I had that when I was drafting this but must have deleted it.

**Comment by samselikoff** [comment]
Crap, I totally forgot about this PR and added some notes to latest this morning. I like your scenarios paragraph, I'll add that in

**Comment by seawatts** [comment]
Awesome! :+1: Thanks for doing this! I can't wait to use it.



On Mon, Jun 1, 2015 at 12:47 PM, Gordon Cassie <notifications@github.com>
wrote:

> Will do - I think I had that when I was drafting this but must have
> deleted it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samselikoff/ember-cli-mirage/pull/143#issuecomment-107683175>
> .
>



-- 
*Chris Watts* | Software Engineer | cwatts@simplymeasured.com

**Comment by g-cassie** [comment]
Ok, sounds good. I will close this.

**Comment by seawatts** [comment]
Is this just going to be merged in the next version?

**Comment by samselikoff** [comment]
i have some local changes, should finish them up + push tonight. I want to have a 0.1.x version of the docs and add new features with a version banner. Instead of adding a new docset for each patch version.

**Comment by seawatts** [comment]
:+1:

On Tue, Jun 9, 2015 at 10:52 AM, Sam Selikoff <notifications@github.com>
wrote:

> i have some local changes, should finish them up + push tonight. I want to
> have a 0.1.x version of the docs and add new features with a version
> banner. Instead of adding a new docset for each patch version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samselikoff/ember-cli-mirage/pull/143#issuecomment-110445471>
> .
>



-- 
*Chris Watts* | Software Engineer | cwatts@simplymeasured.com

**Comment by samselikoff** [comment]
docs added: http://www.ember-cli-mirage.com/docs/v0.1.x/seeding-your-database/#using-factories-in-development

**Pull request closed without merging**
