### PR TITLE
hasMany association cache issue

### PR DESCRIPTION
**Pull request by designblooz**
Not sure why `_cachedChildren` is set on the `ModelClass.prototype` level, but this causes hasMany model factories that were created from the a test to be part of the schema of the model throughout all the test.

To make sure every data is wiped clean after each test, added a method in `server.js` to go through every `ModelClass` to remove `_cachedChildren`.

### CODE REVIEW

**Comment by samselikoff** [comment]
Probably no good reason :) Thanks for digging into this - any chance you could throw together a quick test?

**Comment by designblooz** [comment]
@samselikoff @acorncom added test

**Comment by kategengler** [comment]
Ran into this problem tonight while converting emberobserver over to JSONAPI. Setting the hasMany relationship through `update` _seems_ to be a workaround.

**Comment by samselikoff** [comment]
I recall this being fixed elsewhere

**Pull request closed without merging**
