### PR TITLE
Implemented addon blueprint for ember-cli-mirage that installs bower …

### LINKED ISSUE #108: Use within development of an addon
Is Mirage usable when developing an addon? We are developing a location service that makes API calls to google, testing it has been difficult because we are making ajax calls and we wanted to override those with mirage.

### PR DESCRIPTION
**Pull request by Samsinite**
…deps and copies default structure into tests/dummy/app. Fixes #108

### CODE REVIEW

**Comment by Samsinite** [comment]
Looks like this now creates it in `app/mirage` (from the `ember-cli-mirage` blueprint) as well as in `tests/dummy/app/mirage` (from the `ember-cli-mirage-addon` blueprint). It needs to only install into `tests/dummy/app/mirage` :/. Let me see if I can think of a solution.

**Comment by Samsinite** [comment]
Fixed the issue noticed ^^^ by switching to __root__ and adding the attr under fileMapTokens.

**Comment by Samsinite** [comment]
Also, `tests/dummy/app/(fixtures | factories)/__path__.js` can now be created by specifying the `--dummy` flag. (Ex: `ember g fixture user --dummy` creates `tests/dummy/app/fixtures/user.js`).

**Comment by blimmer** [comment]
ping @samselikoff

**Comment by samselikoff** [comment]
lgtm, thanks so much!

**Comment by samselikoff** [comment]
so, how would one install this in an addon?

**Comment by Samsinite** [comment]
You can run the blueprint like normal, `ember g ember-cli-mirage`, or you can install the addon using `ember install ember-cli-mirage`. Either way will work. For factories and fixtures you'll probably want the `--dummy` option.

**Pull request merged**
