### PR TITLE
Get babel working

### PR DESCRIPTION
**Pull request by cibernox**
Updated to the latest ember-cli (0.2.5) / Ember (0.12) / ED (beta17) and finally I managed to get ES6 working.

I haven't tested in a real app yet, so it's a WIP until I/someone does.

### CODE REVIEW

**Comment by cibernox** [comment]
Ahh, also removed the only usage of prototype extensions.

**Comment by seawatts** [comment]
Woo hoo! :+1:

**Comment by samselikoff** [comment]
oh snap! awesome work. where were we using prototype extensions?

**Comment by cibernox** [comment]
I was using Array#insertAt instead of splice

**Comment by cibernox** [comment]
Ok, I've worked all day with this code linked locally with `npm link` and works great, but there is a failing test only in travis that I cannot reproduce locally. 
Can anyone try to run the suite locally to see if you have more luck?

**Comment by cibernox** [comment]
I'm really clueless about why it's failing in travis but not locally. I was able to reproduce the bug once while I was developing the feature, but when I ran `npm install` it got fixed and now I can't get this failure.

I've tried multiple versions of the dependencies, I've tried to downgrade phantomjs, i've run this in every browser. Any idea?

**Comment by seawatts** [comment]
I'm actually running into this right now. I believe you have to have
phantomjs 2.0.0 installed. And you currently cannot do that with npm

**Comment by cibernox** [comment]
I downgraded to 1.9.8 locally, no luck. I also installed Phantom 2.0 in travis  from a tarball, but still failed. It's something with node/npm, but I can't figure what.

**Comment by samselikoff** [comment]
Sorry I've been busy the last few days, hopefully will take a crack at this
this weekend

**Comment by samselikoff** [comment]
ember tests passing for me too :/ note the node tests aren't (run all with `npm test`)

**Comment by samselikoff** [comment]
travis actually isn't using 2.0, they rolled back a build. We could try updating .travis.yml to manually install 2.0, as described in [this comment](https://github.com/ember-cli/ember-cli/pull/3895#issuecomment-103736634):

```
before_install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
```

want to give it a shot + push, and we'll look at the new build output?

**Comment by cibernox** [comment]
Already did yesterday. No luck

**Comment by cibernox** [comment]
Ok, I've changed the approach. I don't know what the problem is but clearly it's not because of babel. I've reverted all updates except those related with babel and test pass, except those counting the number of trees. 

Not sure how to deal with those tests, i don't fully understand what broccoli is supposed to do with the trees of the addon.

**Comment by samselikoff** [comment]
#161 closes

**Pull request closed without merging**
