### PR TITLE
Added falsy condition to exclude faker.js & pretender.js in production build.

### PR DESCRIPTION
**Pull request by renpinto**
https://github.com/samselikoff/ember-cli-mirage/issues/986

### CODE REVIEW

**Comment by samselikoff** [comment]
All tests pass and I've made you a contributor - you can merge it in as soon as your ready!

I've made an issue to release 0.2.5 if you have more time to help: https://github.com/samselikoff/ember-cli-mirage/issues/988

**Comment by renpinto** [comment]
Thank for that @samselikoff . However I am unable to merge, cannot see the merge button.

**Comment by samselikoff** [comment]
You should have gotten an email with an invitation link. Also try this

https://github.com/samselikoff/ember-cli-mirage/invitations

**Comment by renpinto** [comment]
Got it.. Thank you so much..

**Comment by samselikoff** [comment]
Awesome - want to go ahead and merge? Then we can cut 0.2.5

**Comment by renpinto** [comment]
I have merged it.

**Pull request merged**
