### PR TITLE
Remove lodash dependency from 0.1.x branch.

### PR DESCRIPTION
**Pull request by blimmer**
I have several projects on the 0.1.x branch that I have not had time to upgrade yet

 This PR removes the bower lodash dependency on that branch so that I can remove the bower lodash dependency from projects still on 0.1.x.

### CODE REVIEW

**Comment by samselikoff** [comment]
Thank you v much!

**Comment by samselikoff** [comment]
@blimmer just gave you npm commit bit, feel free to publish anything you need (esp. 0-1 releases)

**Comment by blimmer** [comment]
Thank you @samselikoff ! This is released as 0.1.15.

**Comment by samselikoff** [comment]
🥂

**Pull request merged**
