### PR TITLE
Polymorphic associations

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by fran-worley** [comment]
Could you add some documentation to what has changed with the inverse option? I've just upgraded to 0.3.3 to try out the new polymorphic associations and I'm running into inverse errors on code that ran fine in 0.3.2.

```javascript
// models/committee.js
export default Model.extend({
  meetings: hasMany('meeting'),
  nextMeeting: belongsTo('meeting')  // just need an easy way of accessing the next meeting
});

// models/meetings.js
 export default Model.extend({
  committee: belongsTo({inverse: 'meetings'})
});
```
I now get: `Mirage: The committee model has multiple possible inverse associations for the committee association on the meeting model.`

**Comment by fran-worley** [comment]
It seems to work if I declare the inverse to nextMeeting as null, rather than putting an inverse on the hasMany:

```javascript
// models/committee.js
export default Model.extend({
  meetings: hasMany('meeting'), // access all meetings for committee
  nextMeeting: belongsTo('meeting', {inverse: null})  // easily access the next meeting from meetings collection
});

// models/meetings.js
 export default Model.extend({
  committee: belongsTo()
});
```

**Comment by samselikoff** [comment]
@fran-worley I'm surprised that changed at all from 0.3.2 to 0.3.3 but glad you got it working again.

Are you using the auto-discover feature? Does it work if you get rid of your Mirage models?

**Comment by fran-worley** [comment]
I've just started doing so and it seems to be working ok, great feature 👍!

I more added my comment incase anyone else notices similar funny happenings.

**Pull request merged**
