### PR TITLE
Fix foreign key in factories documentation

### PR DESCRIPTION
**Pull request by balinterdi**

### CODE REVIEW

**Comment by samselikoff** [comment]
Thank you!

**Comment by balinterdi** [comment]
Glad I could contribute back a tiny bit. You helped me tremendously, first by writing an excellent add-on and then helping out with my exact problem (which I'll check this evening).

**Comment by samselikoff** [comment]
:facepunch:

**Comment by balinterdi** [comment]
Facepunch? ;)

**Comment by samselikoff** [comment]
haha should be :fist_bump: but doesn't exist :P

**Pull request merged**
