### PR TITLE
expose build and buildList methods on Server

### PR DESCRIPTION
**Pull request by ballPointPenguin**
This PR would provide https://github.com/samselikoff/ember-cli-mirage/issues/456

### CODE REVIEW

**Comment by samselikoff** [comment]
This is awesome - *great* looking PR, love the test coverage!

I just merged https://github.com/samselikoff/ember-cli-mirage/pull/441. Could you rebase off master + update your `buildList` code to match the `createList` code in there? We were making copies of the db tables when we really didn't need to.

**Comment by ballPointPenguin** [comment]
This is great. Because of #441, build and buildList can take advantage of sequences and auto-increment.
I got to change my silly negative tests like "buildList does not respect sequences" to "buildList respects sequences". Much better :smile_cat:

**Comment by ballPointPenguin** [comment]
I think this is ready to go @samselikoff

**Comment by samselikoff** [comment]
Oh, thanks for the ping! The diff confused me because it showed your work as renaming `create` to `build`, which didn't make sense until I looked more closely. This makes a lot of sense - `create` delegates to `build`, and `build` doesn't need to know about `collection` since it uses the `this.factorySequences` to get the sequence number. Nice work!

**Comment by ballPointPenguin** [comment]
exactly. This came together perfectly with the #441 stuff. Thanks for merging.

**Pull request merged**
