### PR TITLE
Adds ember-suave inline filters + Fixes more linting errors

### PR DESCRIPTION
**Pull request by lependu**
https://github.com/samselikoff/ember-cli-mirage/issues/657#issuecomment-204349715
I think this solves https://github.com/samselikoff/ember-cli-mirage/issues/671#issue-144915155 as well.

### CODE REVIEW

**Comment by samselikoff** [comment]
Awesome, thanks!

What's the `.jscsfilters` file for, global filters? Could we keep it all file-specific? Feels like that's too easy to ignore

**Comment by samselikoff** [comment]
I just saw your comment in the other thread. Is it possible to just use comments at the top of files when we need to override the default settings?

**Comment by lependu** [comment]
the `.jscsfilter` is just a plain text file listing all the filters. I added it because thought  it is hard to track down all the filters if someone wants to review them. But of course I can remove it.

Also updated filters regarding to changes in https://github.com/samselikoff/ember-cli-mirage/commit/13405df8770e496529e19985e9c6c46aed4c82ba

Shall I rebase into 1 commit, or keep commits separeted?

**Comment by lependu** [comment]
One more concern: my npm test results
```
1..1094
tests 1094
pass 1094
skip 0
fail 0
```
while Travis [build #1057](https://travis-ci.org/samselikoff/ember-cli-mirage/builds/120266012) results
```
1..1030
tests 1030
pass  1030
skip  0
fail  0
```
So it seems in Travis still does not run all the tests.

**Comment by samselikoff** [comment]
Sorry if I wasn't clear. I want `requireParenthesesAroundArrowParam` to be `false` globally for the project, because I don't like that rule. But if we have individual files that need to omit a certain rule for some reason, I'd rather do it in the file than in a global file.

Are you saying you cannot have a global change and also apply file-specific overrides? That would surprise me.

**Comment by lependu** [comment]
I am saying you can define global rule in the `.jscrc`, but it will break your tests because https://github.com/DockYard/ember-suave/issues/94. That is why I removed all global rules. And wee need to apply them on file basis as inline filter.

**Comment by samselikoff** [comment]
Ok - so are you happy with this PR? I've been heads down on some other issues so I don't have time to trace through all the references here.

**Comment by lependu** [comment]
Yes, I think this is the best we can do in light of the `ember-suave` issue.

**Comment by samselikoff** [comment]
:+1: thank you

**Pull request merged**
