### PR TITLE
Update ember-cli

### PR DESCRIPTION
**Pull request by eliasmelgaco**
Update ember-cli, async/await ES6 tests, insert test acceptance pets, Remove phantomJS  contribuing.md

### CODE REVIEW

**Comment by eliasmelgaco** [comment]
@samselikoff travis-cli contains a failure. what can we do ?

**Comment by samselikoff** [comment]
Can you rebase off master? I fixed the build

**Comment by samselikoff** [comment]
Could you check if the travis config needs to be updated?

**Comment by jelhan** [comment]
`ember-try` seems to be missing as dependency in `package.json`. It's part of addon new output since `ember-cli@3.0.0`: https://github.com/ember-cli/ember-addon-output/commit/b4b52b9f3d7dbec6ecb01fa7bd6e67cc5ff18428#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R44

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1456 closes

**Pull request closed without merging**
