### PR TITLE
[wip] Allow handlers to be temporarily overridden

### PR DESCRIPTION
**Pull request by elucid**
Extends the server to accept temporary handlers to be used in place of the default handlers defined in `mirage/config.js`. Provides a simple way to stub out server responses within specific
tests to e.g.
- avoid defining complex default handlers for search, sort, filter, pagination, etc.
- test transient error states (see #194)

Temporary handlers are set via `server.queueResponse(verb, path,
handler)`. They are used only once, on the next request to the
matching verb/path pair.

A sequence of temporary handlers can be queued via successive calls to `server.queueResponse()` using the same verb/path pair. They will be run in the order they were queued. Once all temporary handlers in a verb/path queue have been called, subsequent requests to the verb/path pair will be intercepted by the default handler.

**NOTE: Currently a work in progress**

### CODE REVIEW

**Comment by ronco** [comment]
@elucid @samselikoff I'm very interested in seeing this functionality pulled into mirage, any updates?

**Comment by elucid** [comment]
I'm going to have to take a look at the recent changes in mirage and get this working again.

**Comment by g-cassie** [comment]
+1
I would also want to be able to make testing assertions in the temporary handlers to check request data is as expected.  Looking at your code I think this would work without any modifications.

**Comment by samselikoff** [comment]
@rondale-sc expressed renewed interest in this feature. I'm all in favor of adding.

I think the implementation here is sound. I'm wondering if instead of introducing a new API for defining handlers, we can just use the `options` argument that already exists (currently, it only takes `timing`):

```
test('it can recover from an authentication error', function() {
  server.get('/users/current', { some: 'data' }, 500, {
    transient: true
  });

  ...
});
```

**Comment by samselikoff** [comment]
I'm going to close this for now until we can flesh it out a bit more.

If somebody wants to take charge on this issue, let me know (here or in #ec-mirage) and I can help move this forward.

**Comment by nruth** [comment]
@samselikoff I'd like to work on this feature, because we've got tests written like that already that are probably not running the way we thought they were. What needs changing or fleshing out? Docs & using the transient option?

**Comment by localpcguy** [comment]
@samselikoff Like @nruth this is something that is coming up in our app, and curious what needs to happen in order to get this to the point where it would be acceptable? I posted in #ec-mirage also, feel free to respond in whichever place is easier.

**Pull request closed without merging**
