### PR TITLE
Fix mirage directory in addon projects containing in-repo addons

### PR DESCRIPTION
**Pull request by jeloba**
This should address issue #1166.

### CODE REVIEW

**Comment by mattmarcum** [comment]
I just ran into this bug, is there anything I can do to help push this pr fwd?

**Comment by mattmarcum** [comment]
@jeloba can you merge master into your branch to get it up to date?

**Comment by jeloba** [comment]
@mattmarcum here you go

**Comment by mattmarcum** [comment]
@samselikoff this really needs to be merged, its a pretty simple fix

**Comment by samselikoff** [comment]
Thank you @jeloba !

**Pull request merged**
