### PR TITLE
Adds ModelClass.first()

### PR DESCRIPTION
**Pull request by lependu**
Hi. trying to solve #501. This is my 1st contribution, so please go easy on me. Let me know if needs any modification.

### CODE REVIEW

**Comment by samselikoff** [comment]
Awesome, this looks great! Could you rebase, and I'll happily merge this in!

**Comment by lependu** [comment]
Rebased. :+1:

**Comment by samselikoff** [comment]
Thank you! :sparkles:

**Comment by koriroys** [comment]
@samselikoff can close this right? and #501 as well?

**Comment by samselikoff** [comment]
Yes sir, thank you!

**Pull request merged**
