### PR TITLE
[Docs] Fixes variable width on white panel

### PR DESCRIPTION
**Pull request by gcollazo**
screenshot

### CODE REVIEW

**Comment by samselikoff** [comment]
That's bizarre, I'm unable to reproduce. What version of Safari?

`.Container` should have a max-width of 1000px, which should take care of constraining the panel.

**Comment by gcollazo** [comment]
Actually Google Chrome Version 48.0.2564.41 beta (64-bit) on [this page](http://www.ember-cli-mirage.com/docs/v0.1.x/simulating-cookie-responses/).

**Comment by samselikoff** [comment]
Can you inspect and see why `.Container` is not constraining the width?

**Comment by samselikoff** [comment]
I'm seeing this in Canary, it has to do with the `<pre>` tag. We shouldn't just stick a max-width on the white panel, I think. If you'd like to figure out with the flexbox stuff isn't working I'd be happy to merge.

**Comment by gcollazo** [comment]
Tried a few things but couldn't figure out how to fix it without the the `max-width` on the white panel. Feel free to close it.

**Comment by samselikoff** [comment]
Ok. Thanks for your help, hopefully this is a bug in canary since we're not seeing it anywhere else.

**Pull request closed without merging**
