### PR TITLE
Remove reliance on lodash global

### PR DESCRIPTION
**Pull request by HeroicEric**
This removes the usage of the lodash `_` global throughout the codebase and imports used modules instead.

### CODE REVIEW

**Comment by blimmer** [comment]
I think you can also remove the dependency in [bower.json](https://github.com/samselikoff/ember-cli-mirage/blob/master/bower.json#L16), [index.js](https://github.com/samselikoff/ember-cli-mirage/blob/master/index.js#L21), [blueprints index.js](https://github.com/samselikoff/ember-cli-mirage/blob/master/blueprints/ember-cli-mirage/index.js#L37).

Additionally, you'll need to modify the blueprint's index to install `ember-lodash` in the consuming application.

I find it helpful to create an example app ([feel free to use mine](https://travis-ci.org/blimmer/ember-cli-example-app-for-github)), [npm link](https://docs.npmjs.com/cli/link) and test everything works there first.

**Comment by samselikoff** [comment]
I'm for removing globals, but I don't know about the explicit imports of each function. `_.[func]` is super convenient - any good arguments for explicit utility imports? Seems like it would make things annoying to develop (need new function, go look up path, add import statement etc.)

**Comment by john-kurkowski** [comment]
I don't know if Babel does this now, but explicit imports could fail faster. In other words, fail at import time, rather than waiting until call time. 

It does also seem to be the Ember codebase's preference when importing other parts of Ember, versus referencing everything on the `Ember` global. Not sure of their reasons.

¯\_(ツ)_/¯

**Comment by samselikoff** [comment]
Good point, and it does seem to be the direction Ember and others are headed.

@HeroicEric, I'm happy to merge this in if you rebase + address blimmer's points.

**Comment by samselikoff** [comment]
@HeroicEric what do you think?

**Comment by HeroicEric** [comment]
@samselikoff sure. I'll make the updates

**Comment by HeroicEric** [comment]
@samselikoff should be all set

**Comment by samselikoff** [comment]
thank you very much!!

**Comment by HeroicEric** [comment]
@samselikoff I think there was some code that you merged in yesterday that will fail now with these removals :panda_face: I'm not sure why CI didn't warn about this.

I just ran locally and some of them are failing but I'm going to make another PR with the fixes

**Comment by samselikoff** [comment]
Yah I saw -I'm taking care of it locally, no problem man!

**Pull request merged**
