### PR TITLE
add docs for association helper

### PR DESCRIPTION
**Pull request by Azdaroth**

### CODE REVIEW

**Comment by samselikoff** [comment]
Just made you a collab, feel free to merge this!

**Comment by Azdaroth** [comment]
Awesome, thanks! 🍺

**Comment by allthesignals** [comment]
Thanks for adding this. 

I'm just having trouble with this helper following the example from the docs.
```
// factories/feature.js
import { Factory, faker, association } from 'ember-cli-mirage';
...
   city: association()
```

```
// models/feature.js
export default Model.extend({
  city: belongsTo()
});
```

Throws:
```
TypeError: (0 , _emberCliMirage.association) is not a function
    at Module.callback (http://localhost:4200/assets/cityxcity.js:853:119)
    at Module.exports (http://localhost:4200/assets/vendor.js:132:32)
    at requireModule (http://localhost:4200/assets/vendor.js:32:18)
    at http://localhost:4200/assets/vendor.js:157179:20
    at Array.forEach (native)
    at exports.default (http://localhost:4200/assets/vendor.js:157158:8)
    at startMirage (http://localhost:4200/assets/cityxcity.js:513:66)
    at Object.initialize (http://localhost:4200/assets/cityxcity.js:504:9)
    at http://localhost:4200/assets/vendor.js:16148:23
    at http://localhost:4200/assets/vendor.js:16177:16
```

Ember mirage version: "ember-cli-mirage": "0.2.4".

**Comment by allthesignals** [comment]
Maybe this helper just isn't available on npm yet. I changed my package.json to this: `"ember-cli-mirage": "git://github.com/samselikoff/ember-cli-mirage.git"`

**Pull request merged**
