### PR TITLE
Added range function to faker addon

### PR DESCRIPTION
**Pull request by IAmJulianAcosta**
I just created a function that allows to generate a random number between two numbers. Useful for latitude and longitude.

### CODE REVIEW

**Comment by samselikoff** [comment]
awesome! could you add a test? 

https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/unit/faker-test.js

**Comment by IAmJulianAcosta** [comment]
Done! :+1:

**Comment by IAmJulianAcosta** [comment]
@samselikoff where can I update the docs to include this function?

**Comment by samselikoff** [comment]
Awesome, thanks! Can you squash?

`gh-pages` branch (so a separate PR to that branch). Might just be easiest to go to docs site and click the "Improve this doc link". Looks like it's documented on the [factories](http://www.ember-cli-mirage.com/docs/v0.1.x/factories/) page right now.

**Comment by samselikoff** [comment]
woops, what happened?

**Pull request closed without merging**
