### PR TITLE
Fix addon integration

### LINKED ISSUE #524: Mirage is not working with an addon
I'm trying to use Mirage 0.2.0-beta.3 inside an add-on with the dummy app.  The first problem I ran into is:

```
Attempting to watch missing directory: /Users/bhunt/Documents/Code/OpenSource/ember-d3/mirage
Error: Attempting to watch missing directory: /Users/bhunt/Documents/Code/OpenSource/ember-d3/mirage
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:94:35
    at lib$rsvp$$internal$$tryCatch (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/bhunt/Documents/Code/OpenSource/ember-d3/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

If you work around this problem my creating an empty mirage directory at the project root, you then get:

`Uncaught Error: Could not find module dummy/mirage/config imported from dummy/initializers/ember-cli-mirage`

### PR DESCRIPTION
**Pull request by cibernox**
Closes #524 

It depends on / contains #541 (you can merge only this one and close the other if you want)

Honestly, I have no idea how to write a test for this.

### CODE REVIEW

**Comment by samselikoff** [comment]
Rebase + we're ready to go, thanks so much for this. Don't know how to test it either :/

**Comment by cibernox** [comment]
BTW, I did this trying to make an addon using mirage work in fastboot, but I think that this is fundamentally flawed unless pretender.js prepares itself for that. 

Let's see how it goes.

**Comment by samselikoff** [comment]
Hm, interesting... probably because `window` doesn't exist?

**Comment by cibernox** [comment]
I think it was because of `URL`, but probably that is just the first disallowed usage I've found, there will be more.

I'll investigate it more because in order to have meaningful fastboot tests we need to be able to run mirage in node.

**Pull request merged**
