### PR TITLE
DB Supports Querying with a Filter Function

### LINKED ISSUE #365: Update `schema.where` (and `db.where`) to take a filtering function
Right now `schema.user.where(...)` takes an object query, we should also enable it to take a filtering function.

`schema.user.where(u => u.activityCount > 100)`

### PR DESCRIPTION
**Pull request by jherdman**
Querying can now be done with a function in case you want to do super
spicy things with Mirage! Peep this example:

    let legalDrinkersInCanada = db.users.where(function(user) {
      return user.age > 19;
    });

Boom! Resolves #365

### CODE REVIEW

**Comment by samselikoff** [comment]
:boom:

this is awesome--thank you!

**Comment by xamoom-pali** [comment]
Amazing!

**Comment by OakBehringer** [comment]
NOTE: This also works for model.where - docs don't state this; might not be obvious to new users.

**Comment by tumentumurchudur** [comment]
This made my day. Thank you.

**Comment by KeranChen** [comment]
This is great!

**Comment by gbl3** [comment]
Excelent solution, thanks!

**Pull request merged**
