### PR TITLE
Allow FQDN in config

### PR DESCRIPTION
**Pull request by blimmer**
This should unblock our release.

### CODE REVIEW

**Comment by blimmer** [comment]
@samselikoff i'm going to hold off on merging this until you have a chance to confirm the fix.

**Comment by blimmer** [comment]
This is also very similar to @jamesdixon 's #236 , though they are two different implementations. we should figure out which one we want.

**Comment by jamesdixon** [comment]
After looking at your solution, I realized I didn't build in support for using a FQDN directly in the route. That said, I added support for that as well. I'll leave it up to you guys to decide. The one nice thing about being able to set a global prefix is it prevents you from having to set a prefix manually on each route if you happen to be using an external API and don't want to proxy.

Regarding my recent addition, the Travis CI build is still failing on something seemingly unrelated to the updates I made even though everything is passing locally.

**Comment by samselikoff** [comment]
I think being able to have a global prefix is nice, @blimmer any objections?

@jamesdixon could you squash + rebase and we'll investigate the test failures?

**Comment by blimmer** [comment]
As long as we also support a fully qualified url in the config (and that overrides the global prefix), that sounds great! I can imagine a situation where you are mocking an internal api (perhaps with cors) and an external API as well.

**Comment by jamesdixon** [comment]
@blimmer @samselikoff squashed and rebased. The Travis CI build is now passing as well :+1: I had to create a [new PR](https://github.com/samselikoff/ember-cli-mirage/pull/247) as I deleted the master branch of my fork when attempting to squash + rebase and unfortunately, I couldn't reopen the existing PR. Admittedly, it was my first time doing a rebase and ran into a couple of bumps. Let me know if there's anything else you need from me.

**Comment by samselikoff** [comment]
@blimmer yep looked like the test cases supported this case

@jamesdixon rebases are fun :)

**Comment by jamesdixon** [comment]
@samselikoff yeah, definitely a thrilling part of my day :+1:

**Pull request closed without merging**
