### PR TITLE
DEPENDENCY: updated to broccoli-string-replace

### PR DESCRIPTION
**Pull request by toranb**
The [broccoli-replace](https://github.com/outatime/broccoli-replace) library is both vulnerable and unmaintained so this PR migrates over to [broccoli-string-replace](https://github.com/rwjblue/broccoli-string-replace)

Here is the `npm audit` report you get today if you run that command w/ npm 6 after installing this addon. I've spent the weekend removing all references to `broccoli-replace` in other addons to help unlock a perfect 0 vulnerability audit and this will help. Thanks for reviewing!

audit

### CODE REVIEW

**Comment by samselikoff** [comment]
Thanks!

It looks like we have a node test failure... anyone have any ideas why without diving in?

**Comment by toranb** [comment]
@samselikoff  so looking at some source quick it [appears](https://github.com/outaTiME/applause/blob/master/src/applause.js#L177) that the original lib used `applause` to return an object like this ...

```js
  content = content.replace(match, replacement);
  // ... 
  return {
    content: content,
    detail: detail,
    count: total_count
};
```

Then from within the [broccoli-replace](https://github.com/outaTiME/broccoli-replace/blob/master/index.js#L44) library it would pull this off like so

```js
ReplaceFilter.prototype.processString = function(string) {
  var res = this.applause.replace(string);
  var result = res.content;
  var count = res.count;
  if (count === 0) {
    // no replacements
    return string;
  }
  return result;
};
```

From the [simpler broccoli](https://github.com/rwjblue/broccoli-string-replace/blob/master/index.js#L61) library from @rwjblue it would appear much simpler to follow

```js
SimpleReplace.prototype.processString = function (str) {
  for (var i = 0, l = this.patterns.length; i < l; i++) {
    var pattern = this.patterns[i];

    str = str.replace(pattern.match, pattern.replacement);
  }

  return str;
};
```

Looking at the test now and I don't see anything obvious without firing up a inspect debugging session. I'll dive back into this later dudes ;) sorry to punt this PR over and fail to solve this myself Sam

**Comment by toranb** [comment]
screen shot 2018-06-21 at 7 18 42 pm

@rwjblue looks like yours returns an array w/ something called `Minimatch` inside of it. I'm still able to view into that array for what looks like the same assertion output but I'd like to get your take on this when you've got a minute

**Comment by rwjblue** [comment]
Ya, ultimately these tests are a tad too implementation specific IMHO. The changes in this PR seem to function correctly, but the tests in question are failing because of internal details on how the actual broccoli trees are constructed.

My suggestion would be to rewrite [this test file](https://github.com/samselikoff/ember-cli-mirage/blob/master/node-tests/addon-tree-test.js#L26) such that it is using [broccoli-test-helper](https://github.com/broccolijs/broccoli-test-helper) (which has a really nice example with Mocha in its README).

**Comment by samselikoff** [comment]
No it's ok! You can leave it open and others could help with updating the node tests, or you could open an issue for it

**Comment by toranb** [comment]
@samselikoff cool - if anyone has a moment to jump in and rewrite those node tests this should be solid otherwise. I've updated to the `broccoli-replace-string` lib on all of my other addons and as usual :) Robert did a great job so you shouldn't see any impact from the switch

**Comment by samselikoff** [comment]
@rwjblue I've picked this up. How might I assert against which files Mirage includes/excludes in the built `output`? I managed to see the `files.assets` and my dummy.js in there, but are there some examples of asserting against output? It's all concat'd by the time I'm looking at it.

**Comment by samselikoff** [comment]
Perhaps I should be writing tests a bit lower level, against Mirage's broccoli code, rather than using EmberAddon() each time

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1361 supersedes.

Thanks Toran!

**Pull request closed without merging**
