### PR TITLE
Failing test for bug where destroy is leaving db in an invalid state

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by lukemelia** [comment]
Maybe this is the same issue as #1112?

**Comment by lukemelia** [comment]
I've confirmed that this test is fixed by #1113

**Comment by samselikoff** [comment]
working on this right now

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1173 closes

**Comment by samselikoff** [comment]
Thanks for digging into this too :)

**Pull request closed without merging**
