### PR TITLE
IDs as Strings

### LINKED ISSUE #67: db's collection.find should treat ids as strings not numbers
For some background info on why treating IDs as strings instead of numbers is a good ideas, this is a good read: https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake

From an implementation perspective in mirage, we should coerce ids to strings when adding to db, and convert ids to strings when calling `db[collection].find(someId)`

### PR DESCRIPTION
**Pull request by jherdman**
Resolves #67. Please see commits for details. Note also that this requires that #461 be merged first (this pull request exposed the bug), and is presently rebased on top of it.

### CODE REVIEW

**Comment by jherdman** [comment]
Blech. Lots of code churn in this one, it's unavoidable though. It'd be nice to get this in sooner than later as it's likely to cause numerous merge conflicts.

**Comment by samselikoff** [comment]
You're doing the lord's work brother. This looks great. I made a note on the other PR, once we get that in I'm happy to merge this.

Btw, I think because that other commit is part of this PR we could just do this one? It doesn't make a huge difference either way.

**Comment by jherdman** [comment]
> Btw, I think because that other commit is part of this PR we could just do this one? It doesn't make a huge difference either way.

Totally. I'm cool with rolling it into one PR, I figured I'd split it into two in the event this was total garbage :)

**Comment by samselikoff** [comment]
@lukemelia I'd like to get a quick weigh-in from you, if possible. I think this is the right move - it's basically an implementation of [your comment](https://github.com/samselikoff/ember-cli-mirage/issues/67#issuecomment-102394201) from #67.

Don't worry about looking through the entire code diff though, just a quick question. So, I understand that, by ensuring IDs will be stored as strings in Mirage's DB, we'll be able to coerce Mirage's API methods to Always Work: `db.find(1)`, for example, will work without the caller having to know that `1` is actually a string. Same for all the DB methods, and all the Model/Schema methods (`schema.blogPost.find`, etc.).

The one concern I have is when users are calling plain array methods, like filter/sort. Now they need to be aware of the type:

```js
return db.users.filter(user => [1, 3, 4].indexOf(user.id) > -1);
```

Of course, this is not the most realistic example, but it's just to illustrate the point. Although, maybe that is the point, that most of the query methods against IDs will be accounted for by Mirage's `find` APIs. Also, users need to be aware of types when using `:id` from the request itself (e.g., coercing to an INT before matching against the DB), so maybe this is just a fact of life.

What do you think, am I getting the tradeoffs right? I just want to make sure I fully understand so I can communicate the changes to users correctly.

**Comment by lukemelia** [comment]
@samselikoff Yes, I think that captures the tradeoffs well.

**Comment by samselikoff** [comment]
Ok great. Thanks!

**Pull request merged**
