### PR TITLE
[BUGFIX] Blueprint.prototype.insertIntoFile is async

### PR DESCRIPTION
**Pull request by stefanpenner**
This prevents the termination of the process and updating these files from racing.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@samselikoff i believe tests are failure due to node 0.12 stuff, which is EOL. Should i bump node, or move from `=>` to old schol functions + `this` or `bind`

**Comment by samselikoff** [comment]
@stefanpenner bump node would be perfect

**Comment by stefanpenner** [comment]
failing tests appeared to be a bug in ember or ember-data 2.3, bumped to a more recent version and everything appears fine locally. Lets see if CI confirm.

**Comment by samselikoff** [comment]
👏  thank you so much man

**Pull request merged**
