### PR TITLE
adds YUIDoc comments to addon/db.js + updates earlier comments

### PR DESCRIPTION
**Pull request by lizzerdrix**
* continues on #658 
* updates formatting on earlier comments to include `*` on every line
* squashed earlier serializer commit into updated commit because fixing the merge conflict resulted in 2 commits. Seemed better to put them together.

### CODE REVIEW

**Comment by samselikoff** [comment]
Looks great, thanks!

Why `*` on every line, is that part of YUIDoc syntax? I don't see that on Ember's objects/API docs

**Comment by lizzerdrix** [comment]
You can see it in the YUIDoc syntax guide: http://yui.github.io/yuidoc/syntax/

I don't know why I didn't notice it before (probably because I was looking at the Ember docs). If you want me to revert, that's totally fine!

**Comment by samselikoff** [comment]
Nice catch - looks like JSDoc also does this so I'm :+1: on this change.

Thanks again for all your help!

**Comment by samselikoff** [comment]
Shoot. I keep doing this, I pressed the "merge" button but I wanted to keep these commits separate. 

Sorry!

**Pull request merged**
