### PR TITLE
Update ember cli 2.9

### PR DESCRIPTION
**Pull request by cibernox**
Holy ****. I thought this would be just 5 minutes 😞 

I had to disable some ESLint rules because the amount of errors was just staggering.

### CODE REVIEW

**Comment by cibernox** [comment]
@samselikoff Can you clear the caches in travis? I have no idea why `ember try:one` is failing.

**Comment by cibernox** [comment]
@samselikoff Ignore my previous comment.

**Comment by cibernox** [comment]
Any clue why those namespace tests might pass in chrome/ffox/safari but not in phantom?

**Comment by samselikoff** [comment]
holy **** is right

**Comment by samselikoff** [comment]
it looks like you removed the travis code that pointed to Phantom JS 2.0

**Comment by samselikoff** [comment]
not sure why i closed..woops. sorry.

**Comment by cibernox** [comment]
I have the latest version of phantomjs locally that the exact same tests fail with a timeout, but no error is shown. I'll try to track this this weekend, I asked in case you knew from the top of your head what part of the code could lead to a `$.getJSON()` never resolving or failing.

**Comment by cibernox** [comment]
After checking it today, I have a few suspects, in order of suspicion:

I've noticed that the pretender handled is never called, but no idea why yet.

- The removal of `baseURL` from the document
- The update to jquery 3

**Comment by locks** [comment]
@cibernox my money's on jQuery 3

**Comment by samselikoff** [comment]
anything I can do to support this? We shouldn't let it get too far from `master`, you did a ton of work

**Comment by samselikoff** [comment]
#1008 closes.

Thank the Lord.

**Pull request closed without merging**
